/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { StayEscrow, StayEscrowInterface } from "../StayEscrow";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "payee",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "weiAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "spaceId",
        type: "bytes32",
      },
    ],
    name: "Deposited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "payee",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "weiAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "spaceId",
        type: "bytes32",
      },
    ],
    name: "Withdrawn",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "payee",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "spaceId",
        type: "bytes32",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "payee",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "spaceId",
        type: "bytes32",
      },
    ],
    name: "depositsOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "payee",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "spaceId",
        type: "bytes32",
      },
    ],
    name: "depositsState",
    outputs: [
      {
        internalType: "enum StayEscrow.State",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class StayEscrow__factory {
  static readonly abi = _abi;
  static createInterface(): StayEscrowInterface {
    return new utils.Interface(_abi) as StayEscrowInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StayEscrow {
    return new Contract(address, _abi, signerOrProvider) as StayEscrow;
  }
}
